### ISSUE TITLE
Add more CSS Loader

### ISSUE THREAD

**Issue by AjayMaheshwari23** [rohit8020/css-loaders#36]
I want to add a CSS loader , can i ? 
assign this issue to me

**Comment by AjayMaheshwari23** [comment]
Oh , i think I can directly make a PR for a loader .
By mistake , i have created  this issue , please close this .

**Comment by rohit8020** [comment]
> Oh , i think I can directly make a PR for a loader . By mistake , i have created this issue , please close this .

Yeah, You can directly make  a  PR after adding the CSS Loader, after review, I will merge it.
