### ISSUE TITLE
[FEATURE] Seperate codes array to json file

### ISSUE THREAD

**Issue by vikasganiga05** [rohit8020/css-loaders#48]
Hi, I suggest separating the codes array in the `index.js` file into a JSON file. Then using the fetch method to get the requested codes for the css-loader in `index.js`.

I like to work on this issue.

**Comment by rohit8020** [comment]
> Hi, I suggest separating the codes array in the `index.js` file into a JSON file. Then using the fetch method to get the requested codes for the css-loader in `index.js`.
> 
> I like to work on this issue.

Hi @vikasganiga05,
The idea sounds great, make the separate JSON file and add fetch functionality, it will be great.
Make the PR, I will merge the PR if it will work fine.
Thanks!

**Comment by vikasganiga05** [comment]
I will start working on it as soon as possible. Thanks!
