### ISSUE TITLE
Add more loaders

### ISSUE THREAD

**Issue by AdithiDesai** [rohit8020/css-loaders#76]

**Comment by AdithiDesai** [comment]
I would like to work on this. Can you assign this to me?

**Comment by rohit8020** [comment]
> I would like to work on this. Can you assign this to me?

You can contribute to this project by adding a new CSS-Loader, to be sure to follow the [rules](https://github.com/rohit8020/css-loaders/blob/main/README.md).

**Comment by AdithiDesai** [comment]
@rohit8020 I have finished this task. Here is the screenshot. The last two loaders were added by me. Can you assign it to me so that I can do a pull request?
![Screenshot (136)](https://user-images.githubusercontent.com/103984059/196031404-14eed234-5688-452d-8b53-5d33580c1dc2.png)

**Comment by AdithiDesai** [comment]
@rohit8020 Can you see my pull request #77?
